### ISSUE TITLE
How to use the bam format SV result for "bayestyper genotyping" software??

### ISSUE THREAD

**Issue by Sherry520** [zeeev/smartie-sv#8]
I compared two similar species SV use smartie, then I want to use these SVs to genotype in a population with "bayestyper genotyping" software, But "bayestyper genotyping" only support for vcf format, What should I do ???

**Comment by zeeev** [comment]
You can write a conversion script. I'll look to see if I have one.

**Comment by Sherry520** [comment]
ok

**Comment by Sherry520** [comment]
I still have difficulty  converting the bam to vcf. how to get "contig" information? Bayestyper requires the vcf header to contain contig entries (e.g.##contig=<ID=8,length=146364022>) for all reference sequences containing variants in the vcf
